export const FETCH_EXPENSES = 'FETCH_EXPENSES';
export const NEW_EXPENSE = 'NEW_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const NEW_CATEGORY = 'NEW_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';